### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Pyario** [mastercake10/uShop#1]
Can you add a feature?

If you sell things but have no value, you get the items again?

The best that you can put it in the config on or off.

Mfg

**Comment by mastercake10** [comment]
I'm not sure if I got your question right, but items that aren't defined won't be sold.

**Comment by Pyario** [comment]
sell-prices-simple:
- ACACIA_LOG:1.0


I only have that in the config. But if I have other items inside, he will sell them automatically

**Comment by Pyario** [comment]
ENGLISH TEXT:

I have seen SRC that you ask if an item is not Custom that you get it again.
Is it possible that you add there if the item has no value so 0.0 has that
you get that again? I hope you understand what i mean.

Best Regards,
Pyario

GERMAN TEXT:

Ich habe SRC gesehen das du abfragst ob ein Item was nicht Custom ist das man das wieder bekommt.
Ist es möglich das du dort noch hinzufügst das wenn das Item was keine Wert hat also 0.0 hat das 
man das das auch wieder bekommt? Ich hoffe du verstehst was ich meine.

Mit freundlichen Grüßen,

Pyario.

**Comment by mastercake10** [comment]
see #9
