### ISSUE TITLE
essentials-worth-list not working

### ISSUE THREAD

**Issue by PortGasMC** [mastercake10/uShop#10]
### What steps will reproduce the issue?  
1. use-essentials-worth-list: true not working 

### What was supposed to happen?
1. will not use the essentials worth price even if you set to "true in uShop config

### What happened instead? 
1. Nothing happens

### What version of this plugin are you using?  
1. latest uShop version

### What Spigot version are you using? Paste the output of /version below.  
1. 1.14.4 paper spigot

### What plugins do you have installed? Paste the output of /plugins below. 

AdvancedRegionMarket, BeastWithDraw, BountyHunters, ChestCleaner, ChestShop*, Citizens, CitizensCMD, CrazyCrates, CustomEnchants*, DeluxeMenus, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, EZBlocks*, eZProtector, FeatherBoard*, Holograms*, LeaderHeadsRevamped, mcMMO, MessageFilter*, Minepacks, Multiverse-Core, MVdWPlaceholderAPI*, NametagEdit*, PermissionsEx*, PlaceholderAPI, ProtocolLib, RandomTeleport, RawMsg, RedProtect, RFChairs, SilkSpawners, StackMob, uShop, SuperTrails*, TempFly*, TitleManager*, Trading*, Vault, VeinMiner, ViaVersion*, VillagerOptimiser, VoidGenerator, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldResetPlus*

### Are any errors related to this plugin in your console or logs? If so, paste below.  
```  
no errors on console
```

**Comment by inxanedev** [comment]
Same issue but on 1.12.2 spigot, using 1.7.6 uShop.

**Comment by Epykest** [comment]
Same issue here as well.

**Comment by mastercake10** [comment]
use `/ushop convert` in the new version.
