### ISSUE TITLE
Essentials Worth not working

### ISSUE THREAD

**Issue by inxanedev** [mastercake10/uShop#11]
### What steps will reproduce the issue?  
1. Install 1.7.6 uShop
2. Install latest Essentials
3. Try to sell any items
### What was supposed to happen?
Plugin should use Essentials's worth.yml file for the item prices.
### What happened instead? 
Did not load them, errors in the console. All items were worth $0 and even when I clicked the Sell button, it errored out again and the gui was still open but without the golden nugget.
### What version of this plugin are you using?  
1.7.6
### What Spigot version are you using? Paste the output of /version below.  
 version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### What plugins do you have installed? Paste the output of /plugins below.  
ChatItem, CoreProtect, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncVoxelSniper, FastAsyncWorldEdit, iDisguise, jNBT, LuckPerms, Multiverse-Core, MySkin, OpenInv, PlaceholderAPI, ProtocolLib, Skellett, SkQuery, skRayFall, Skript, skUtilities, SuperVanish, TuSKe, Vault, VoxelSniper, WorldEdit, WorldGuard

### Are any errors related to this plugin in your console or logs? If so, paste below.  
```
https://pastebin.com/raw/baim9TSy
```
### Any additional information that you would like to provide that may be relevant to the issue?
From what I'm seeing in the errors, it tries to access a method in the Essentials plugin api which doesn't exist. com.earth2me.essentials.Worth.getPrice is the method.
If the method really doesn't exist (the method got removed) then there is not much you can do about this issue apart from loading both the aliases of the items and then parse the worth.yml file directly.

Please fix this issue as this plugin is perfect for me and I think a lot of people, would be awesome to have this fixed.

**Comment by mastercake10** [comment]
MC 1.12.2 is not supported anymore.
