### ISSUE TITLE
Glowing items are not salable

### ISSUE THREAD

**Issue by mastercake10** [mastercake10/uShop#15]
### What steps will reproduce the issue?  
1. set a price on a glowing item
2. try to sell it

### What was supposed to happen?
Item is salable

### What happened instead? 
Item is not salable

### What version of this plugin are you using?  
latest

### Are any errors related to this plugin in your console or logs? If so, paste below.  
```
paste
error(s)
here
```

**Comment by AmCharley** [comment]
have you tried adding the item to the shop through a command? 
```
/ushop add <price> [Flags ...]
```
This command works on items with and without item meta.
flags:
```
- ignore_enchantments
- ignore_durability 
- ignore_lore
- ignore_displayname
- ignore_meta
```
