### ISSUE TITLE
uShop bug

### ISSUE THREAD

**Issue by IronDirt** [mastercake10/uShop#18]
I voted 5 stars because I really like this plugin but after 30 min it doesn't show how much each product is worth anymore when you want to sell it.
"Pardon my English"
To resolve temporarily I'm using the command /plugman reload uShop" every 30 min automatically from another plugin
gg

**Comment by Hermiten** [comment]
I think there is a big memory leak because my server crash every time after 2-3 hours with the plugin.
I use Paper-211 (1.15.2) and last version of uShop on Spigot

**Comment by AmCharley** [comment]
this plugin could do with a new update. the idea of this plugin is great but the execution with the latest versions of a paper isn't great. still a good, easy to use plugin though.
