### ISSUE TITLE
Serveur crash

### ISSUE THREAD

**Issue by jeannen** [mastercake10/uShop#6]
Hey !

It seems like there is a spigot crash because of the plugin. I'm using spigot 1.14.2, and the lastest version of the plugin. Here are the logs:
https://pastebin.com/gdfz770j

**Comment by mcannie97** [comment]
I can confirm this issue, I have it on my 1.14.4 paper (175) server too
Since I removed the plugin I haven't had lag issues or crashes
plugin version: 2.1.0
errors: https://pastebin.com/7fHhQPzM

**Comment by Coolkc456** [comment]
I came here because of this, too. I'm gonna have to find another shop plugin because of this. I actually have to kill my server and restart to fix the issue until it happens again...
https://pastebin.com/0hMtTJtS

**Comment by Epykest** [comment]
I am on 1.14.4 and it crashes apparently a user said they had placed the an item (perhaps the how to claim land book by GriefPrevention) and some other items in and instead of clicking Sell, they hit ESC.

https://pastebin.com/raw/AC2iS6bp is what it showed.
